[2023-10-05T03:53:49.629+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Reddit_Post_Comment_Dag.extract_post_comment_task manual__2023-10-05T03:49:46.943241+00:00 [queued]>
[2023-10-05T03:53:49.674+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Reddit_Post_Comment_Dag.extract_post_comment_task manual__2023-10-05T03:49:46.943241+00:00 [queued]>
[2023-10-05T03:53:49.676+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-10-05T03:53:49.731+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_post_comment_task> on 2023-10-05 03:49:46.943241+00:00
[2023-10-05T03:53:49.755+0000] {standard_task_runner.py:57} INFO - Started process 635 to run task
[2023-10-05T03:53:49.769+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Reddit_Post_Comment_Dag', 'extract_post_comment_task', 'manual__2023-10-05T03:49:46.943241+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/reddit_post_comment_dag.py', '--cfg-path', '/tmp/tmp_82zn8db']
[2023-10-05T03:53:49.788+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask extract_post_comment_task
[2023-10-05T03:53:49.958+0000] {task_command.py:415} INFO - Running <TaskInstance: Reddit_Post_Comment_Dag.extract_post_comment_task manual__2023-10-05T03:49:46.943241+00:00 [running]> on host 1de4a8047cc3
[2023-10-05T03:53:50.146+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Reddit_Post_Comment_Dag' AIRFLOW_CTX_TASK_ID='extract_post_comment_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T03:49:46.943241+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-05T03:49:46.943241+00:00'
[2023-10-05T03:53:50.165+0000] {logging_mixin.py:151} INFO - ['xr8fc3', 'rco8xd', 'pou8vz', 'pa07hq', 'p9283m', 'ntnjz2', 'mi9q3t', 'kdmatx', 'k2qgn2', '3gscwr']
[2023-10-05T03:55:47.586+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/reddit_data_extractor.py", line 94, in extract_post_comment
    post_comments["post_id"].append(post.id)
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/models/reddit/base.py", line 35, in __getattr__
    self._fetch()
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/models/reddit/comment.py", line 192, in _fetch
    raise ClientException(f"No data returned for comment {self.fullname}")
praw.exceptions.ClientException: No data returned for comment _
[2023-10-05T03:55:47.604+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Reddit_Post_Comment_Dag, task_id=extract_post_comment_task, execution_date=20231005T034946, start_date=20231005T035349, end_date=20231005T035547
[2023-10-05T03:55:47.630+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 53 for task extract_post_comment_task (No data returned for comment _; 635)
[2023-10-05T03:55:47.669+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-05T03:55:47.731+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
