[2023-10-04T02:17:42.232+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Reddit_Post_Dag.raw_data_insert_task manual__2023-10-04T02:17:33.915667+00:00 [queued]>
[2023-10-04T02:17:42.248+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Reddit_Post_Dag.raw_data_insert_task manual__2023-10-04T02:17:33.915667+00:00 [queued]>
[2023-10-04T02:17:42.250+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-04T02:17:42.270+0000] {taskinstance.py:1382} INFO - Executing <Task(RawDataTableOperator): raw_data_insert_task> on 2023-10-04 02:17:33.915667+00:00
[2023-10-04T02:17:42.278+0000] {standard_task_runner.py:57} INFO - Started process 68 to run task
[2023-10-04T02:17:42.285+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Reddit_Post_Dag', 'raw_data_insert_task', 'manual__2023-10-04T02:17:33.915667+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/reddit_post_dag.py', '--cfg-path', '/tmp/tmp4zy18676']
[2023-10-04T02:17:42.292+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask raw_data_insert_task
[2023-10-04T02:17:42.373+0000] {task_command.py:415} INFO - Running <TaskInstance: Reddit_Post_Dag.raw_data_insert_task manual__2023-10-04T02:17:33.915667+00:00 [running]> on host 119fbdffdc04
[2023-10-04T02:17:42.701+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Reddit_Post_Dag' AIRFLOW_CTX_TASK_ID='raw_data_insert_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-04T02:17:33.915667+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-04T02:17:33.915667+00:00'
[2023-10-04T02:17:42.703+0000] {raw_data_table_operator.py:27} INFO - Executing CustomMySqlOperator with data from task: extract_post_task
[2023-10-04T02:17:42.718+0000] {sql.py:274} INFO - Executing: CREATE TABLE IF NOT EXISTS test(id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) DEFAULT NULL,score INT DEFAULT NULL,post_id INT DEFAULT NULL,url VARCHAR(255) DEFAULT NULL,comms_num INT DEFAULT NULL,created DATETIME DEFAULT NULL, body TEXT DEFAULT NULL,author VARCHAR(255) DEFAULT NULL,subreddit VARCHAR(255) DEFAULT NULL)
[2023-10-04T02:17:42.725+0000] {base.py:73} INFO - Using connection ID 'mysql_connection' for task execution.
[2023-10-04T02:17:42.736+0000] {base.py:73} INFO - Using connection ID 'mysql_connection' for task execution.
[2023-10-04T02:17:42.767+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/raw_data_table_operator.py", line 31, in execute
    self.create_table(context)
  File "/opt/airflow/plugins/raw_data_table_operator.py", line 44, in create_table
    create_task.execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/mysql/hooks/mysql.py", line 188, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 193, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1044, "Access denied for user '***'@'%' to database 'social_media_assignment'")
[2023-10-04T02:17:42.783+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Reddit_Post_Dag, task_id=raw_data_insert_task, execution_date=20231004T021733, start_date=20231004T021742, end_date=20231004T021742
[2023-10-04T02:17:42.800+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task raw_data_insert_task ((1044, "Access denied for user '***'@'%' to database 'social_media_assignment'"); 68)
[2023-10-04T02:17:42.821+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-04T02:17:42.847+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
