[2023-10-05T03:49:51.469+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Reddit_Post_Comment_Dag.extract_post_comment_task manual__2023-10-05T03:49:46.943241+00:00 [queued]>
[2023-10-05T03:49:51.485+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Reddit_Post_Comment_Dag.extract_post_comment_task manual__2023-10-05T03:49:46.943241+00:00 [queued]>
[2023-10-05T03:49:51.487+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-05T03:49:51.521+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_post_comment_task> on 2023-10-05 03:49:46.943241+00:00
[2023-10-05T03:49:51.534+0000] {standard_task_runner.py:57} INFO - Started process 575 to run task
[2023-10-05T03:49:51.541+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Reddit_Post_Comment_Dag', 'extract_post_comment_task', 'manual__2023-10-05T03:49:46.943241+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/reddit_post_comment_dag.py', '--cfg-path', '/tmp/tmp5qdba2za']
[2023-10-05T03:49:51.548+0000] {standard_task_runner.py:85} INFO - Job 52: Subtask extract_post_comment_task
[2023-10-05T03:49:51.640+0000] {task_command.py:415} INFO - Running <TaskInstance: Reddit_Post_Comment_Dag.extract_post_comment_task manual__2023-10-05T03:49:46.943241+00:00 [running]> on host 1de4a8047cc3
[2023-10-05T03:49:51.759+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Reddit_Post_Comment_Dag' AIRFLOW_CTX_TASK_ID='extract_post_comment_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T03:49:46.943241+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-05T03:49:46.943241+00:00'
[2023-10-05T03:49:51.781+0000] {logging_mixin.py:151} INFO - ['xr8fc3', 'rco8xd', 'pou8vz', 'pa07hq', 'p9283m', 'ntnjz2', 'mi9q3t', 'kdmatx', 'k2qgn2', '3gscwr']
[2023-10-05T03:52:46.378+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/reddit_data_extractor.py", line 94, in extract_post_comment
    post_comments["comment_auther"].append(comment_data.author)
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/models/reddit/base.py", line 35, in __getattr__
    self._fetch()
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/models/reddit/comment.py", line 192, in _fetch
    raise ClientException(f"No data returned for comment {self.fullname}")
praw.exceptions.ClientException: No data returned for comment _
[2023-10-05T03:52:46.396+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Reddit_Post_Comment_Dag, task_id=extract_post_comment_task, execution_date=20231005T034946, start_date=20231005T034951, end_date=20231005T035246
[2023-10-05T03:52:46.424+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 52 for task extract_post_comment_task (No data returned for comment _; 575)
[2023-10-05T03:52:46.462+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-05T03:52:46.496+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
