[2023-10-04T02:13:52.913+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Reddit_Post_Dag.raw_data_insert_task manual__2023-10-04T02:12:45.198777+00:00 [queued]>
[2023-10-04T02:13:52.946+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Reddit_Post_Dag.raw_data_insert_task manual__2023-10-04T02:12:45.198777+00:00 [queued]>
[2023-10-04T02:13:52.949+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-10-04T02:13:52.985+0000] {taskinstance.py:1382} INFO - Executing <Task(RawDataTableOperator): raw_data_insert_task> on 2023-10-04 02:12:45.198777+00:00
[2023-10-04T02:13:53.001+0000] {standard_task_runner.py:57} INFO - Started process 3164 to run task
[2023-10-04T02:13:53.015+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Reddit_Post_Dag', 'raw_data_insert_task', 'manual__2023-10-04T02:12:45.198777+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/reddit_post_dag.py', '--cfg-path', '/tmp/tmpt6hjcycr']
[2023-10-04T02:13:53.025+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask raw_data_insert_task
[2023-10-04T02:13:53.155+0000] {task_command.py:415} INFO - Running <TaskInstance: Reddit_Post_Dag.raw_data_insert_task manual__2023-10-04T02:12:45.198777+00:00 [running]> on host a82955aebbba
[2023-10-04T02:13:53.514+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Reddit_Post_Dag' AIRFLOW_CTX_TASK_ID='raw_data_insert_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-04T02:12:45.198777+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-04T02:12:45.198777+00:00'
[2023-10-04T02:13:53.516+0000] {raw_data_table_operator.py:27} INFO - Executing CustomMySqlOperator with data from task: extract_post_task
[2023-10-04T02:13:53.537+0000] {sql.py:274} INFO - Executing: CREATE TABLE IF NOT EXISTS test(id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) DEFAULT NULL,score INT DEFAULT NULL,post_id INT DEFAULT NULL,url VARCHAR(255) DEFAULT NULL,comms_num INT DEFAULT NULL,created DATETIME DEFAULT NULL, body TEXT DEFAULT NULL,author VARCHAR(255) DEFAULT NULL,subreddit VARCHAR(255) DEFAULT NULL)
[2023-10-04T02:13:53.544+0000] {base.py:73} INFO - Using connection ID 'mysql_connection' for task execution.
[2023-10-04T02:13:53.556+0000] {base.py:73} INFO - Using connection ID 'mysql_connection' for task execution.
[2023-10-04T02:13:53.575+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/raw_data_table_operator.py", line 31, in execute
    self.create_table(context)
  File "/opt/airflow/plugins/raw_data_table_operator.py", line 44, in create_table
    create_task.execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/mysql/hooks/mysql.py", line 188, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 193, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1044, "Access denied for user '***'@'%' to database 'social_media_assignment'")
[2023-10-04T02:13:53.591+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Reddit_Post_Dag, task_id=raw_data_insert_task, execution_date=20231004T021245, start_date=20231004T021352, end_date=20231004T021353
[2023-10-04T02:13:53.609+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task raw_data_insert_task ((1044, "Access denied for user '***'@'%' to database 'social_media_assignment'"); 3164)
[2023-10-04T02:13:53.669+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-04T02:13:53.719+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
