[2023-10-03T14:55:44.886+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Reddit_Post_Dag.extract_post_task manual__2023-10-03T14:55:41.945895+00:00 [queued]>
[2023-10-03T14:55:44.902+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Reddit_Post_Dag.extract_post_task manual__2023-10-03T14:55:41.945895+00:00 [queued]>
[2023-10-03T14:55:44.904+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-03T14:55:44.923+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_post_task> on 2023-10-03 14:55:41.945895+00:00
[2023-10-03T14:55:44.933+0000] {standard_task_runner.py:57} INFO - Started process 271 to run task
[2023-10-03T14:55:44.939+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Reddit_Post_Dag', 'extract_post_task', 'manual__2023-10-03T14:55:41.945895+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/reddit_post_dag.py', '--cfg-path', '/tmp/tmp5tdywn73']
[2023-10-03T14:55:44.946+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask extract_post_task
[2023-10-03T14:55:45.039+0000] {task_command.py:415} INFO - Running <TaskInstance: Reddit_Post_Dag.extract_post_task manual__2023-10-03T14:55:41.945895+00:00 [running]> on host a82955aebbba
[2023-10-03T14:55:45.172+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Reddit_Post_Dag' AIRFLOW_CTX_TASK_ID='extract_post_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-03T14:55:41.945895+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-03T14:55:41.945895+00:00'
[2023-10-03T14:55:46.612+0000] {logging_mixin.py:151} INFO -                                                title  ...  subreddit
0                            THEY WON THE UNION VOTE  ...  starbucks
1                 60 Frappuccino‚Äôs with no tip‚Ä¶ $279  ...  starbucks
2             I'm not allowed to make signs anymore.  ...  starbucks
3                        What did you get fired for?  ...  starbucks
4                        An inspiration to us all üôåüèª  ...  starbucks
5  when they buy a $0.05 handle bag and request a...  ...  starbucks
6                Filling out the CoVid CoAcH like...  ...  starbucks
7                                bro is struggling üíÄ  ...  starbucks
8   Needless to say we‚Äôve been verbally abused a lot  ...  starbucks
9  Year two of dressing up as In-N-Out at my Star...  ...  starbucks

[10 rows x 9 columns]
[2023-10-03T14:55:46.634+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/reddit_data_extractor.py", line 51, in extract_post_data
    posts_df.to_csv(csv_file_path, index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/data/raw'
[2023-10-03T14:55:46.655+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Reddit_Post_Dag, task_id=extract_post_task, execution_date=20231003T145541, start_date=20231003T145544, end_date=20231003T145546
[2023-10-03T14:55:46.679+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task extract_post_task (Cannot save file into a non-existent directory: '/data/raw'; 271)
[2023-10-03T14:55:46.705+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-03T14:55:46.748+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
